class Action {
    static STOP_TASK = 'STOP_TASK';
    static START_TASK_EDITING_VIDEO = 'START_TASK_EDITING_VIDEO';
    static STATUS_VIDEO_EDITING = 'STATUS_VIDEO_EDITING';
    static FAIL_TASK = 'FAIL_TASK';
    static DONE_TASK = 'DONE_TASK';
    static SEND_MESSAGE_APP = 'SEND_MESSAGE_APP';
    static DOWNLOAD_FILE = 'DOWNLOAD_FILE';
    static SCAN_VIDEO_DOUYIN = 'SCAN_VIDEO_DOUYIN';
    static PROCESS_DOWNLOAD_FILE = 'PROCESS_DOWNLOAD_FILE';
    static GET_COOKIE_INSTAGRAM = 'GET_COOKIE_INSTAGRAM';
    static COMMENT_POSTED_REELS = 'COMMENT_POSTED_REELS';
    static COMMENT_POSTED_REELS_SUCCESS = 'COMMENT_POSTED_REELS_SUCCESS';
    static COMMENT_POSTED_REELS_FAILURE = 'COMMENT_POSTED_REELS_FAILURE';
    static SCAN_VIDEO_TIKTOK_BY_USER_NAME = 'SCAN_VIDEO_TIKTOK_BY_USER_NAME';
    static GET_ITEM_LIST_TIKTOK = 'GET_ITEM_LIST_TIKTOK';
    static SCAN_REACT_ACCOUNT = 'SCAN_REACT_ACCOUNT';
    static GET_DATA_REACT_ACCOUNT = 'GET_DATA_REACT_ACCOUNT';
    static POST_VIDEO_ZALO_CREATOR = 'POST_VIDEO_ZALO_CREATOR';
    static PROGRESS_POST_VIDEO_ZALO_CREATOR = 'PROGRESS_POST_VIDEO_ZALO_CREATOR';
    static POST_VIDEO_REELS_FB_CHROME = 'POST_VIDEO_REELS_FB_CHROME';
    static GET_COOKIE_FULL_YT = 'GET_COOKIE_FULL_YT';
}

class ChannelName {
    static IS_VIDEO_POSTED = 'IS_VIDEO_POSTED';
    static GET_PRODUCT_CTA = 'GET_PRODUCT_CTA';
    static GET_TODAY_VIDEO_UPLOAD_TIME = 'GET_TODAY_VIDEO_UPLOAD_TIME';
    static UPDATE_COOKIE_ACCOUNT = 'UPDATE_COOKIE_ACCOUNT';
}

module.exports = { Action, ChannelName };